### ISSUE TITLE
print-env ignores values for downward API variables

### ISSUE THREAD

**Issue by ledroide** [pedrobarco/kubectl-env#11]
Many environment variables actually available inside the pod are not displayed by print-env, and variables populated by the downward API display no value (nevertheless they actually have correct values inside the pod).

```bash
$ kubectl print-env pod/rabbitmq-0 -nqube | egrep ^MY_
MY_POD_NAMESPACE=
MY_POD_NAME=
MY_POD_IP=

$ kubectl exec -ti pod/rabbitmq-0 -n qube -- printenv | egrep ^MY_
MY_POD_NAMESPACE=qube
MY_POD_NAME=rabbitmq-0
MY_POD_IP=10.233.115.59

$ kubectl krew info print-env
[...]
URI: https://github.com/pedrobarco/kubectl-print-env/releases/download/v0.1.2/kubectl-print-env_v0.1.2_linux_amd64.tar.gz
SHA256: b2ff1e7f8cac626b3eecdea25ef76e956387a0c5aaccac3b88145139df6f9b91
VERSION: v0.1.2
```

You can reproduce it when declaring an environment variable from the downward API, this way :
```yaml
spec:
  templates:
    spec:
      containers:
        - name: rabbitmq
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
```
